// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escrow/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OfferListAllRequest struct {
}

func (m *OfferListAllRequest) Reset()         { *m = OfferListAllRequest{} }
func (m *OfferListAllRequest) String() string { return proto.CompactTextString(m) }
func (*OfferListAllRequest) ProtoMessage()    {}
func (*OfferListAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d37bf65b8b6e159, []int{0}
}
func (m *OfferListAllRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OfferListAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OfferListAllRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OfferListAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferListAllRequest.Merge(m, src)
}
func (m *OfferListAllRequest) XXX_Size() int {
	return m.Size()
}
func (m *OfferListAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferListAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OfferListAllRequest proto.InternalMessageInfo

type QueryOfferByIDRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryOfferByIDRequest) Reset()         { *m = QueryOfferByIDRequest{} }
func (m *QueryOfferByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOfferByIDRequest) ProtoMessage()    {}
func (*QueryOfferByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d37bf65b8b6e159, []int{1}
}
func (m *QueryOfferByIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOfferByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOfferByIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOfferByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOfferByIDRequest.Merge(m, src)
}
func (m *QueryOfferByIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOfferByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOfferByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOfferByIDRequest proto.InternalMessageInfo

func (m *QueryOfferByIDRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryOfferByAddrRequest struct {
	Offerer string `protobuf:"bytes,1,opt,name=offerer,proto3" json:"offerer,omitempty"`
}

func (m *QueryOfferByAddrRequest) Reset()         { *m = QueryOfferByAddrRequest{} }
func (m *QueryOfferByAddrRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOfferByAddrRequest) ProtoMessage()    {}
func (*QueryOfferByAddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d37bf65b8b6e159, []int{2}
}
func (m *QueryOfferByAddrRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOfferByAddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOfferByAddrRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOfferByAddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOfferByAddrRequest.Merge(m, src)
}
func (m *QueryOfferByAddrRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOfferByAddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOfferByAddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOfferByAddrRequest proto.InternalMessageInfo

func (m *QueryOfferByAddrRequest) GetOfferer() string {
	if m != nil {
		return m.Offerer
	}
	return ""
}

type OfferListResponse struct {
	OfferList []*Offer `protobuf:"bytes,1,rep,name=offerList,proto3" json:"offerList,omitempty"`
}

func (m *OfferListResponse) Reset()         { *m = OfferListResponse{} }
func (m *OfferListResponse) String() string { return proto.CompactTextString(m) }
func (*OfferListResponse) ProtoMessage()    {}
func (*OfferListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d37bf65b8b6e159, []int{3}
}
func (m *OfferListResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OfferListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OfferListResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OfferListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferListResponse.Merge(m, src)
}
func (m *OfferListResponse) XXX_Size() int {
	return m.Size()
}
func (m *OfferListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OfferListResponse proto.InternalMessageInfo

func (m *OfferListResponse) GetOfferList() []*Offer {
	if m != nil {
		return m.OfferList
	}
	return nil
}

func init() {
	proto.RegisterType((*OfferListAllRequest)(nil), "escrow.OfferListAllRequest")
	proto.RegisterType((*QueryOfferByIDRequest)(nil), "escrow.QueryOfferByIDRequest")
	proto.RegisterType((*QueryOfferByAddrRequest)(nil), "escrow.QueryOfferByAddrRequest")
	proto.RegisterType((*OfferListResponse)(nil), "escrow.OfferListResponse")
}

func init() { proto.RegisterFile("escrow/query.proto", fileDescriptor_6d37bf65b8b6e159) }

var fileDescriptor_6d37bf65b8b6e159 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4e, 0x02, 0x31,
	0x18, 0xc5, 0x29, 0x44, 0x0c, 0x35, 0xa2, 0xd4, 0x10, 0x11, 0xb5, 0x92, 0xd9, 0x48, 0x62, 0x32,
	0x4d, 0xe0, 0x02, 0x42, 0xdc, 0xa8, 0x44, 0xe3, 0x2c, 0xdd, 0x0d, 0x4c, 0x81, 0x26, 0x63, 0xbf,
	0xa1, 0x2d, 0x91, 0xb9, 0x85, 0xc7, 0x72, 0xc9, 0xd2, 0xa5, 0x81, 0x0b, 0x78, 0x04, 0xc3, 0x0c,
	0x03, 0x8c, 0x12, 0x96, 0x7d, 0xef, 0xd7, 0xf7, 0xfd, 0xc3, 0x84, 0xeb, 0x9e, 0x82, 0x77, 0x36,
	0x1a, 0x73, 0x15, 0xda, 0x81, 0x02, 0x03, 0x24, 0x1f, 0x6b, 0xd5, 0x8b, 0x01, 0xc0, 0xc0, 0xe7,
	0xcc, 0x0d, 0x04, 0x73, 0xa5, 0x04, 0xe3, 0x1a, 0x01, 0x52, 0xc7, 0x54, 0xf5, 0x68, 0xf9, 0xd3,
	0x4c, 0x62, 0xc1, 0x2a, 0xe3, 0x93, 0xe7, 0x7e, 0x9f, 0xab, 0x8e, 0xd0, 0xa6, 0xe5, 0xfb, 0x0e,
	0x1f, 0x8d, 0xb9, 0x36, 0xd6, 0x35, 0x2e, 0xbf, 0x2c, 0xc2, 0x23, 0xaf, 0x1d, 0xde, 0xdf, 0x2d,
	0x0d, 0x52, 0xc4, 0x59, 0xe1, 0x55, 0x50, 0x0d, 0xd5, 0x73, 0x4e, 0x56, 0x78, 0x56, 0x13, 0x9f,
	0x6e, 0x82, 0x2d, 0xcf, 0x53, 0x09, 0x5a, 0xc1, 0xfb, 0xb0, 0x50, 0xb9, 0x8a, 0xf8, 0x82, 0x93,
	0x3c, 0xad, 0x5b, 0x5c, 0x5a, 0x15, 0x75, 0xb8, 0x0e, 0x40, 0x6a, 0x4e, 0x6e, 0x70, 0x01, 0x12,
	0xb1, 0x82, 0x6a, 0xb9, 0xfa, 0x41, 0xe3, 0xd0, 0x8e, 0xdb, 0xb5, 0x23, 0xda, 0x59, 0xfb, 0x8d,
	0x1f, 0x84, 0xf7, 0xa2, 0xba, 0xe4, 0x11, 0x97, 0xd6, 0x0d, 0x2c, 0xa7, 0x20, 0xe7, 0xa9, 0x8f,
	0xe9, 0xd9, 0xaa, 0x67, 0xff, 0xcc, 0x55, 0x0f, 0x0f, 0xb8, 0x98, 0x1e, 0x9b, 0x5c, 0x26, 0xf0,
	0xd6, 0x75, 0xec, 0xca, 0x7a, 0xc2, 0xc7, 0x7f, 0x37, 0x43, 0xae, 0xb6, 0xa5, 0x6d, 0xec, 0x6c,
	0x47, 0x5e, 0xbb, 0xf3, 0x39, 0xa3, 0x68, 0x3a, 0xa3, 0xe8, 0x7b, 0x46, 0xd1, 0xc7, 0x9c, 0x66,
	0xa6, 0x73, 0x9a, 0xf9, 0x9a, 0xd3, 0xcc, 0x6b, 0x63, 0x20, 0xcc, 0x70, 0xdc, 0xb5, 0x7b, 0xf0,
	0xc6, 0x84, 0x34, 0x5c, 0xf5, 0x86, 0xae, 0x90, 0x5d, 0xae, 0x7c, 0x21, 0x59, 0x00, 0xe0, 0x1b,
	0x08, 0xd9, 0x84, 0x25, 0xa7, 0x0f, 0x03, 0xae, 0xbb, 0xf9, 0xe8, 0xfc, 0xcd, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x12, 0x03, 0x73, 0x9f, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	QueryOfferListAll(ctx context.Context, in *OfferListAllRequest, opts ...grpc.CallOption) (*OfferListResponse, error)
	QueryOfferByID(ctx context.Context, in *QueryOfferByIDRequest, opts ...grpc.CallOption) (*OfferListResponse, error)
	QueryOfferByAddr(ctx context.Context, in *QueryOfferByAddrRequest, opts ...grpc.CallOption) (*OfferListResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryOfferListAll(ctx context.Context, in *OfferListAllRequest, opts ...grpc.CallOption) (*OfferListResponse, error) {
	out := new(OfferListResponse)
	err := c.cc.Invoke(ctx, "/escrow.Query/QueryOfferListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryOfferByID(ctx context.Context, in *QueryOfferByIDRequest, opts ...grpc.CallOption) (*OfferListResponse, error) {
	out := new(OfferListResponse)
	err := c.cc.Invoke(ctx, "/escrow.Query/QueryOfferByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryOfferByAddr(ctx context.Context, in *QueryOfferByAddrRequest, opts ...grpc.CallOption) (*OfferListResponse, error) {
	out := new(OfferListResponse)
	err := c.cc.Invoke(ctx, "/escrow.Query/QueryOfferByAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	QueryOfferListAll(context.Context, *OfferListAllRequest) (*OfferListResponse, error)
	QueryOfferByID(context.Context, *QueryOfferByIDRequest) (*OfferListResponse, error)
	QueryOfferByAddr(context.Context, *QueryOfferByAddrRequest) (*OfferListResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryOfferListAll(ctx context.Context, req *OfferListAllRequest) (*OfferListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOfferListAll not implemented")
}
func (*UnimplementedQueryServer) QueryOfferByID(ctx context.Context, req *QueryOfferByIDRequest) (*OfferListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOfferByID not implemented")
}
func (*UnimplementedQueryServer) QueryOfferByAddr(ctx context.Context, req *QueryOfferByAddrRequest) (*OfferListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOfferByAddr not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryOfferListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryOfferListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escrow.Query/QueryOfferListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryOfferListAll(ctx, req.(*OfferListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryOfferByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOfferByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryOfferByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escrow.Query/QueryOfferByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryOfferByID(ctx, req.(*QueryOfferByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryOfferByAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOfferByAddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryOfferByAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escrow.Query/QueryOfferByAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryOfferByAddr(ctx, req.(*QueryOfferByAddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "escrow.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryOfferListAll",
			Handler:    _Query_QueryOfferListAll_Handler,
		},
		{
			MethodName: "QueryOfferByID",
			Handler:    _Query_QueryOfferByID_Handler,
		},
		{
			MethodName: "QueryOfferByAddr",
			Handler:    _Query_QueryOfferByAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "escrow/query.proto",
}

func (m *OfferListAllRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OfferListAllRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OfferListAllRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryOfferByIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOfferByIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOfferByIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryOfferByAddrRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOfferByAddrRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOfferByAddrRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Offerer) > 0 {
		i -= len(m.Offerer)
		copy(dAtA[i:], m.Offerer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Offerer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OfferListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OfferListResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OfferListResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OfferList) > 0 {
		for iNdEx := len(m.OfferList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfferList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OfferListAllRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryOfferByIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryOfferByAddrRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Offerer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *OfferListResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OfferList) > 0 {
		for _, e := range m.OfferList {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OfferListAllRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OfferListAllRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OfferListAllRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOfferByIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOfferByIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOfferByIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOfferByAddrRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOfferByAddrRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOfferByAddrRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offerer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Offerer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OfferListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OfferListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OfferListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfferList = append(m.OfferList, &Offer{})
			if err := m.OfferList[len(m.OfferList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
