// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: faucet/history.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MintHistory struct {
	Minter   string `protobuf:"bytes,1,opt,name=minter,proto3" json:"minter,omitempty"`
	Lasttime int64  `protobuf:"varint,2,opt,name=lasttime,proto3" json:"lasttime,omitempty"`
	Tally    int64  `protobuf:"varint,3,opt,name=tally,proto3" json:"tally,omitempty"`
}

func (m *MintHistory) Reset()         { *m = MintHistory{} }
func (m *MintHistory) String() string { return proto.CompactTextString(m) }
func (*MintHistory) ProtoMessage()    {}
func (*MintHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4ed2d52d72725e5, []int{0}
}
func (m *MintHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintHistory.Merge(m, src)
}
func (m *MintHistory) XXX_Size() int {
	return m.Size()
}
func (m *MintHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_MintHistory.DiscardUnknown(m)
}

var xxx_messageInfo_MintHistory proto.InternalMessageInfo

func (m *MintHistory) GetMinter() string {
	if m != nil {
		return m.Minter
	}
	return ""
}

func (m *MintHistory) GetLasttime() int64 {
	if m != nil {
		return m.Lasttime
	}
	return 0
}

func (m *MintHistory) GetTally() int64 {
	if m != nil {
		return m.Tally
	}
	return 0
}

func init() {
	proto.RegisterType((*MintHistory)(nil), "faucet.MintHistory")
}

func init() { proto.RegisterFile("faucet/history.proto", fileDescriptor_f4ed2d52d72725e5) }

var fileDescriptor_f4ed2d52d72725e5 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0xb3, 0x1e, 0x06, 0x5d, 0xbb, 0x10, 0x24, 0x97, 0x62, 0x39, 0xac, 0xae, 0xba, 0x01,
	0x7d, 0x03, 0x2b, 0x0b, 0x6d, 0xae, 0x11, 0x6c, 0x64, 0x13, 0xf6, 0x36, 0x0b, 0x9b, 0x9d, 0x90,
	0x9d, 0x80, 0x79, 0x0b, 0x1f, 0xcb, 0xf2, 0x4a, 0x4b, 0x49, 0x5e, 0x44, 0xdc, 0x5d, 0xec, 0xe6,
	0xfb, 0x66, 0xf8, 0x67, 0x18, 0x5e, 0x9e, 0xe4, 0xd4, 0x2a, 0x82, 0xce, 0x78, 0xc2, 0x71, 0x3e,
	0x0c, 0x23, 0x12, 0x16, 0x79, 0xb4, 0xf5, 0xb6, 0x45, 0xdf, 0xa3, 0x7f, 0x0f, 0x16, 0x22, 0xc4,
	0x91, 0xba, 0xd4, 0xa8, 0x31, 0xfa, 0xbf, 0x2a, 0xd9, 0xad, 0x46, 0xd4, 0x56, 0x41, 0xa0, 0x66,
	0x3a, 0x81, 0x74, 0x29, 0xf3, 0xee, 0x95, 0xdf, 0xbc, 0x18, 0x47, 0x4f, 0x71, 0x51, 0x71, 0xcb,
	0xf3, 0xde, 0x38, 0x52, 0x63, 0xc5, 0x76, 0x6c, 0x7f, 0x7d, 0x4c, 0x54, 0xd4, 0xfc, 0xca, 0x4a,
	0x4f, 0x64, 0x7a, 0x55, 0x5d, 0xec, 0xd8, 0x7e, 0x73, 0xfc, 0xe7, 0xa2, 0xe4, 0x97, 0x24, 0xad,
	0x9d, 0xab, 0x4d, 0x68, 0x44, 0x78, 0x7c, 0xfe, 0x5a, 0x04, 0x3b, 0x2f, 0x82, 0xfd, 0x2c, 0x82,
	0x7d, 0xae, 0x22, 0x3b, 0xaf, 0x22, 0xfb, 0x5e, 0x45, 0xf6, 0x76, 0xaf, 0x0d, 0x75, 0x53, 0x73,
	0x68, 0xb1, 0x87, 0x90, 0xde, 0x76, 0xd2, 0xb8, 0x46, 0x8d, 0xd6, 0x38, 0x18, 0x10, 0x2d, 0xe1,
	0x0c, 0x1f, 0x90, 0x5e, 0x40, 0xf3, 0xa0, 0x7c, 0x93, 0x87, 0x6b, 0x1f, 0x7e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x34, 0x80, 0x0a, 0x19, 0x01, 0x00, 0x00,
}

func (m *MintHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintHistory) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintHistory) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tally != 0 {
		i = encodeVarintHistory(dAtA, i, uint64(m.Tally))
		i--
		dAtA[i] = 0x18
	}
	if m.Lasttime != 0 {
		i = encodeVarintHistory(dAtA, i, uint64(m.Lasttime))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Minter) > 0 {
		i -= len(m.Minter)
		copy(dAtA[i:], m.Minter)
		i = encodeVarintHistory(dAtA, i, uint64(len(m.Minter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHistory(dAtA []byte, offset int, v uint64) int {
	offset -= sovHistory(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MintHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Minter)
	if l > 0 {
		n += 1 + l + sovHistory(uint64(l))
	}
	if m.Lasttime != 0 {
		n += 1 + sovHistory(uint64(m.Lasttime))
	}
	if m.Tally != 0 {
		n += 1 + sovHistory(uint64(m.Tally))
	}
	return n
}

func sovHistory(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHistory(x uint64) (n int) {
	return sovHistory(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MintHistory) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHistory
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHistory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHistory
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHistory
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Minter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lasttime", wireType)
			}
			m.Lasttime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHistory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lasttime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tally", wireType)
			}
			m.Tally = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHistory
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tally |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHistory(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHistory
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHistory(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHistory
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHistory
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHistory
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHistory
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHistory
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHistory
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHistory        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHistory          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHistory = fmt.Errorf("proto: unexpected end of group")
)
