// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: faucet/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryWhenBrrRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryWhenBrrRequest) Reset()         { *m = QueryWhenBrrRequest{} }
func (m *QueryWhenBrrRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWhenBrrRequest) ProtoMessage()    {}
func (*QueryWhenBrrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{0}
}
func (m *QueryWhenBrrRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhenBrrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhenBrrRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhenBrrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhenBrrRequest.Merge(m, src)
}
func (m *QueryWhenBrrRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhenBrrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhenBrrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhenBrrRequest proto.InternalMessageInfo

func (m *QueryWhenBrrRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryWhenBrrResponse struct {
	TimeLeft int64 `protobuf:"varint,1,opt,name=timeLeft,proto3" json:"timeLeft,omitempty"`
}

func (m *QueryWhenBrrResponse) Reset()         { *m = QueryWhenBrrResponse{} }
func (m *QueryWhenBrrResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWhenBrrResponse) ProtoMessage()    {}
func (*QueryWhenBrrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{1}
}
func (m *QueryWhenBrrResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWhenBrrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWhenBrrResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWhenBrrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWhenBrrResponse.Merge(m, src)
}
func (m *QueryWhenBrrResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWhenBrrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWhenBrrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWhenBrrResponse proto.InternalMessageInfo

func (m *QueryWhenBrrResponse) GetTimeLeft() int64 {
	if m != nil {
		return m.TimeLeft
	}
	return 0
}

type QueryEmojiRankRequest struct {
}

func (m *QueryEmojiRankRequest) Reset()         { *m = QueryEmojiRankRequest{} }
func (m *QueryEmojiRankRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmojiRankRequest) ProtoMessage()    {}
func (*QueryEmojiRankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{2}
}
func (m *QueryEmojiRankRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmojiRankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmojiRankRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmojiRankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmojiRankRequest.Merge(m, src)
}
func (m *QueryEmojiRankRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmojiRankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmojiRankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmojiRankRequest proto.InternalMessageInfo

type QueryEmojiRankResponse struct {
	Rank []*Amount `protobuf:"bytes,1,rep,name=rank,proto3" json:"rank,omitempty"`
}

func (m *QueryEmojiRankResponse) Reset()         { *m = QueryEmojiRankResponse{} }
func (m *QueryEmojiRankResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmojiRankResponse) ProtoMessage()    {}
func (*QueryEmojiRankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{3}
}
func (m *QueryEmojiRankResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmojiRankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmojiRankResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmojiRankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmojiRankResponse.Merge(m, src)
}
func (m *QueryEmojiRankResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmojiRankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmojiRankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmojiRankResponse proto.InternalMessageInfo

func (m *QueryEmojiRankResponse) GetRank() []*Amount {
	if m != nil {
		return m.Rank
	}
	return nil
}

type Amount struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Total   int64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{4}
}
func (m *Amount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return m.Size()
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Amount) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryWhenBrrRequest)(nil), "faucet.QueryWhenBrrRequest")
	proto.RegisterType((*QueryWhenBrrResponse)(nil), "faucet.QueryWhenBrrResponse")
	proto.RegisterType((*QueryEmojiRankRequest)(nil), "faucet.QueryEmojiRankRequest")
	proto.RegisterType((*QueryEmojiRankResponse)(nil), "faucet.QueryEmojiRankResponse")
	proto.RegisterType((*Amount)(nil), "faucet.Amount")
}

func init() { proto.RegisterFile("faucet/query.proto", fileDescriptor_32e01ab1e3e8ff22) }

var fileDescriptor_32e01ab1e3e8ff22 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xb1, 0xae, 0xd3, 0x30,
	0x14, 0x4d, 0xde, 0xe3, 0x15, 0x30, 0xe8, 0x0d, 0x26, 0x40, 0x5e, 0x28, 0x51, 0x95, 0xa9, 0x53,
	0x2c, 0x85, 0x85, 0x81, 0x85, 0x4a, 0x6c, 0x5d, 0x9a, 0x05, 0x89, 0x05, 0x39, 0xa9, 0x9b, 0x9a,
	0x26, 0xbe, 0xa9, 0xed, 0x08, 0x2a, 0xc4, 0xc2, 0x17, 0x20, 0xf1, 0x45, 0x6c, 0x8c, 0x95, 0x58,
	0x18, 0x51, 0xcb, 0x87, 0xa0, 0xda, 0x2e, 0x7a, 0xad, 0xda, 0xcd, 0xe7, 0x1e, 0x9f, 0x7b, 0xce,
	0xbd, 0xba, 0x08, 0xcf, 0x68, 0x57, 0x32, 0x4d, 0x96, 0x1d, 0x93, 0xab, 0xb4, 0x95, 0xa0, 0x01,
	0xf7, 0x6c, 0x2d, 0xba, 0x29, 0x41, 0x35, 0xa0, 0xde, 0x9b, 0x2a, 0xb1, 0xc0, 0x7e, 0x89, 0xfa,
	0x15, 0x40, 0x55, 0x33, 0x42, 0x5b, 0x4e, 0xa8, 0x10, 0xa0, 0xa9, 0xe6, 0x20, 0xf6, 0x6c, 0x50,
	0x41, 0x05, 0x56, 0xb5, 0x7b, 0xb9, 0xea, 0x8d, 0xd3, 0x18, 0x54, 0x74, 0x33, 0x42, 0x85, 0x73,
	0x4c, 0x08, 0x7a, 0x34, 0xd9, 0x05, 0x78, 0x3b, 0x67, 0x62, 0x24, 0x65, 0xce, 0x96, 0x1d, 0x53,
	0x1a, 0x87, 0xe8, 0x2e, 0x9d, 0x4e, 0x25, 0x53, 0x2a, 0xf4, 0x07, 0xfe, 0xf0, 0x7e, 0xbe, 0x87,
	0x49, 0x86, 0x82, 0x43, 0x81, 0x6a, 0x41, 0x28, 0x86, 0x23, 0x74, 0x4f, 0xf3, 0x86, 0x8d, 0xd9,
	0x4c, 0x1b, 0xc9, 0x65, 0xfe, 0x1f, 0x27, 0x4f, 0xd1, 0x63, 0xa3, 0x79, 0xd3, 0xc0, 0x07, 0x9e,
	0x53, 0xb1, 0x70, 0x36, 0xc9, 0x2b, 0xf4, 0xe4, 0x98, 0x70, 0xed, 0x12, 0x74, 0x47, 0x52, 0xb1,
	0x08, 0xfd, 0xc1, 0xe5, 0xf0, 0x41, 0x76, 0x9d, 0xda, 0xc5, 0xa4, 0xaf, 0x1b, 0xe8, 0x84, 0xce,
	0x0d, 0x97, 0xbc, 0x44, 0x3d, 0x8b, 0xcf, 0xc7, 0xc5, 0x01, 0xba, 0xd2, 0xa0, 0x69, 0x1d, 0x5e,
	0x98, 0x4c, 0x16, 0x64, 0x3f, 0x7c, 0x74, 0x65, 0x8c, 0x31, 0x43, 0x0f, 0x6f, 0x8f, 0x83, 0x9f,
	0xed, 0x9d, 0x4e, 0x6c, 0x25, 0xea, 0x9f, 0x26, 0x6d, 0xe4, 0x24, 0xfa, 0xfa, 0xeb, 0xef, 0xf7,
	0x8b, 0x00, 0x63, 0xf2, 0xd1, 0x32, 0xe4, 0xb3, 0x4b, 0xf1, 0x05, 0x4f, 0xd0, 0xf5, 0xe1, 0xa0,
	0xf8, 0xf9, 0x41, 0xaf, 0xe3, 0xcd, 0x44, 0xf1, 0x39, 0xda, 0x99, 0x79, 0xa3, 0xf1, 0xcf, 0x4d,
	0xec, 0xaf, 0x37, 0xb1, 0xff, 0x67, 0x13, 0xfb, 0xdf, 0xb6, 0xb1, 0xb7, 0xde, 0xc6, 0xde, 0xef,
	0x6d, 0xec, 0xbd, 0xcb, 0x2a, 0xae, 0xe7, 0x5d, 0x91, 0x96, 0xd0, 0x10, 0x2e, 0x34, 0x93, 0xe5,
	0x9c, 0x72, 0x51, 0x30, 0x59, 0x73, 0x41, 0x5a, 0x80, 0x5a, 0xc3, 0x8a, 0x7c, 0x22, 0xee, 0xfe,
	0xf4, 0xaa, 0x65, 0xaa, 0xe8, 0x99, 0x73, 0x78, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x1a,
	0x9f, 0x6b, 0x96, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// WhenBrr queries the last time an address minted
	QueryWhenBrr(ctx context.Context, in *QueryWhenBrrRequest, opts ...grpc.CallOption) (*QueryWhenBrrResponse, error)
	QueryEmojiRank(ctx context.Context, in *QueryEmojiRankRequest, opts ...grpc.CallOption) (*QueryEmojiRankResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryWhenBrr(ctx context.Context, in *QueryWhenBrrRequest, opts ...grpc.CallOption) (*QueryWhenBrrResponse, error) {
	out := new(QueryWhenBrrResponse)
	err := c.cc.Invoke(ctx, "/faucet.Query/QueryWhenBrr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryEmojiRank(ctx context.Context, in *QueryEmojiRankRequest, opts ...grpc.CallOption) (*QueryEmojiRankResponse, error) {
	out := new(QueryEmojiRankResponse)
	err := c.cc.Invoke(ctx, "/faucet.Query/QueryEmojiRank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// WhenBrr queries the last time an address minted
	QueryWhenBrr(context.Context, *QueryWhenBrrRequest) (*QueryWhenBrrResponse, error)
	QueryEmojiRank(context.Context, *QueryEmojiRankRequest) (*QueryEmojiRankResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryWhenBrr(ctx context.Context, req *QueryWhenBrrRequest) (*QueryWhenBrrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryWhenBrr not implemented")
}
func (*UnimplementedQueryServer) QueryEmojiRank(ctx context.Context, req *QueryEmojiRankRequest) (*QueryEmojiRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEmojiRank not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryWhenBrr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWhenBrrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryWhenBrr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faucet.Query/QueryWhenBrr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryWhenBrr(ctx, req.(*QueryWhenBrrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryEmojiRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmojiRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryEmojiRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faucet.Query/QueryEmojiRank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryEmojiRank(ctx, req.(*QueryEmojiRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faucet.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryWhenBrr",
			Handler:    _Query_QueryWhenBrr_Handler,
		},
		{
			MethodName: "QueryEmojiRank",
			Handler:    _Query_QueryEmojiRank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faucet/query.proto",
}

func (m *QueryWhenBrrRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhenBrrRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhenBrrRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWhenBrrResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWhenBrrResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWhenBrrResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeLeft != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TimeLeft))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEmojiRankRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmojiRankRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmojiRankRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmojiRankResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmojiRankResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmojiRankResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rank) > 0 {
		for iNdEx := len(m.Rank) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rank[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Amount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Amount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Amount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryWhenBrrRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWhenBrrResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeLeft != 0 {
		n += 1 + sovQuery(uint64(m.TimeLeft))
	}
	return n
}

func (m *QueryEmojiRankRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmojiRankResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rank) > 0 {
		for _, e := range m.Rank {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *Amount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Total != 0 {
		n += 1 + sovQuery(uint64(m.Total))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryWhenBrrRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhenBrrRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhenBrrRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWhenBrrResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWhenBrrResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWhenBrrResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLeft", wireType)
			}
			m.TimeLeft = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeLeft |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmojiRankRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmojiRankRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmojiRankRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmojiRankResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmojiRankResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmojiRankResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rank", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rank = append(m.Rank, &Amount{})
			if err := m.Rank[len(m.Rank)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Amount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Amount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Amount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
