package types

import (
	"github.com/cosmos/cosmos-sdk/codec"
	cdctypes "github.com/cosmos/cosmos-sdk/codec/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/msgservice"
)

// RegisterCodec registers concrete types on codec
func RegisterCodec(cdc *codec.LegacyAmino) {
	// this line is used by starport scaffolding
	// cdc.RegisterConcrete(MsgCreateUser{}, "pooltoy/CreateUser", nil)
}

func RegisterInterfaces(registry cdctypes.InterfaceRegistry) {
	// TODO:this is generated by pb.go
	msgservice.RegisterMsgServiceDesc(registry, &_Msg_serviceDesc)

	//	registry.RegisterImplementations((*sdk.Msg)(nil), &MsgSend{})
	registry.RegisterImplementations((*sdk.Msg)(nil), &MsgCreateUser{})
}

// ModuleCdc defines the module codec
var (
	amino = codec.NewLegacyAmino()
	cdc   = codec.NewAminoCodec(amino)
)
